/* global monogatari, MygoChapter */
'use strict';

// 由生成第一关.py 从第一题 v1.5 定稿编译；请在文案源和演出映射中维护。
monogatari.assets("scenes", {"bg_kisaragi_passage": "第一关/bg_kisaragi_passage.webp", "bg_kisaragi_platform-no1": "第一关/bg_kisaragi_platform-no1.webp", "bg_kisaragi_platform-pillar": "第一关/bg_kisaragi_platform-pillar.webp", "bg_kisaragi_platform": "第一关/bg_kisaragi_platform.webp", "bg_passage_loop_bad": "第一关/bg_passage_loop_bad.webp", "bg_train_interior_night-dim": "第一关/bg_train_interior_night-dim.webp", "bg_train_interior_night-passing": "第一关/bg_train_interior_night-passing.webp", "bg_train_interior_night": "第一关/bg_train_interior_night.webp", "bg_train_sleepers_L": "第一关/bg_train_sleepers_L.webp", "bg_train_sleepers_R": "第一关/bg_train_sleepers_R.webp", "bg_yaneoka_concourse_night-dawn": "第一关/bg_yaneoka_concourse_night-dawn.webp", "bg_yaneoka_concourse_night": "第一关/bg_yaneoka_concourse_night.webp", "bg_yaneoka_passage": "第一关/bg_yaneoka_passage.webp", "bg_yaneoka_platform_dawn": "第一关/bg_yaneoka_platform_dawn.webp", "bg_yaneoka_platform_night-bright": "第一关/bg_yaneoka_platform_night-bright.webp", "bg_yaneoka_platform_night-off": "第一关/bg_yaneoka_platform_night-off.webp", "bg_yaneoka_platform_night": "第一关/bg_yaneoka_platform_night.webp", "cg_arrival": "第一关/cg_arrival.webp", "cg_badend": "第一关/cg_badend.webp", "cg_boarding": "第一关/cg_boarding.webp", "cg_passing": "第一关/cg_passing.webp", "cg_photo": "第一关/cg_photo.webp", "cg_reunion": "第一关/cg_reunion.webp", "cg_run_loop": "第一关/cg_run_loop.webp", "cg_sign": "第一关/cg_sign.webp", "cg_signal": "第一关/cg_signal.webp", "cg_title": "第一关/cg_title.webp", "cg_train_head": "第一关/cg_train_head.webp"});
monogatari.assets("music", {"reunion": "第一关/重逢_温暖钢琴.mp3", "mystery": "第一关/如月站_暗色氛围.mp3"});
monogatari.assets("sounds", {"station_wind": "第一关/空站_轻风.mp3", "train_rumble": "第一关/列车_车厢轰鸣.mp3", "camera": "第一关/手机_拍照快门.mp3", "notification": "第一关/手机_消息通知.mp3", "station_signal": "第一关/列车_三短一长.mp3"});
monogatari.configuration("credits", {"制作人员": {"制作人": ["SHALOM_紫糕"], "致谢": ["TechnoRabbitXiaoQing235"], "演员": ["千早爱音", "椎名立希", "高松灯", "如月车站"]}, "音频素材": {"背景音乐": ["Calm Piano 1 (Vaporware) — cynicmusic / The Cynic Project — CC0 — opengameart.org/content/calm-piano-1-vaporware", "Dark Ambient Loop 13 — Lucas Calvo / MundoSound — CC-BY 3.0 — opengameart.org/content/dark-ambient-loop-13"], "音效": ["Background Rumble Noise — gryc — CC-BY 3.0 — opengameart.org/content/background-rumble-noise — 已剪辑循环", "Mild Wind Background Noise — Bashar3A — CC0", "Camera — themightyglider — CC0", "Interface Sounds — Kenney — CC0"]}, "声明": ["仅用于CTF赛事，非商用", "剧情仅供娱乐"]});
monogatari.characters({"anon": {"name": "千早爱音", "color": "#f4a8c4", "directory": "第一关_image25", "sprites": {"apologetic": "sp_anon_apologetic.webp", "cheer": "sp_anon_cheer.webp", "clutch_sleeve": "sp_anon_clutch_sleeve.webp", "count_beats": "sp_anon_count_beats.webp", "excited": "sp_anon_excited.webp", "lean_whisper": "sp_anon_lean_whisper.webp", "look_phone": "sp_anon_look_phone.webp", "normal": "sp_anon_normal.webp", "photo": "sp_anon_photo.webp", "pout": "sp_anon_pout.webp", "press_window": "sp_anon_press_window.webp", "scared": "sp_anon_scared.webp", "shock": "sp_anon_shock.webp", "show_screen": "sp_anon_show_screen.webp", "sly": "sp_anon_sly.webp", "soft": "sp_anon_soft.webp", "strained": "sp_anon_strained.webp", "teary": "sp_anon_teary.webp", "tease": "sp_anon_tease.webp"}}, "taki": {"name": "椎名立希", "color": "#c9aff4", "directory": "第一关_image25", "sprites": {"block_wind": "sp_taki_block_wind.webp", "drum_knees": "sp_taki_drum_knees.webp", "faint_smile": "sp_taki_faint_smile.webp", "focus": "sp_taki_focus.webp", "frown": "sp_taki_frown.webp", "gentle": "sp_taki_gentle.webp", "guilt": "sp_taki_guilt.webp", "knock": "sp_taki_knock.webp", "lean_in": "sp_taki_lean_in.webp", "look_away": "sp_taki_look_away.webp", "normal": "sp_taki_normal.webp", "point_map": "sp_taki_point_map.webp", "reach_back": "sp_taki_reach_back.webp", "sharp": "sp_taki_sharp.webp", "shy": "sp_taki_shy.webp", "slow_turn": "sp_taki_slow_turn.webp", "stiff": "sp_taki_stiff.webp", "watery": "sp_taki_watery.webp"}}, "tomori": {"name": "高松灯", "color": "#a4cfe9", "directory": "第一关_image25", "sprites": {"blank": "sp_tomori_blank.webp", "earnest": "sp_tomori_earnest.webp", "hug_bag": "sp_tomori_hug_bag.webp", "pull_sleeves": "sp_tomori_pull_sleeves.webp", "reach_hand": "sp_tomori_reach_hand.webp", "show_phone": "sp_tomori_show_phone.webp", "small_smile": "sp_tomori_small_smile.webp", "stand": "sp_tomori_stand.webp", "steady": "sp_tomori_steady.webp", "write_memo": "sp_tomori_write_memo.webp"}}});
monogatari.script({
"Start": [
  function () { return MygoChapter.begin(); },
  "jump Scene1"
],
"Scene1": [
  function () { return MygoChapter.enter("Scene1"); },
  "show scene bg_yaneoka_platform_night with fadeIn",
  "排练散场的时候，立希说鼓棒忘在了练习室，还特意交代灯\"不用等我，先回家\"。灯点了点头，应了一声。",
  "我因为补光夹落在长椅边折回来——站台上就只有立希一个人，整座车站，安静得能听见空调的风。",
  "show character taki normal at right",
  "show character anon normal at left",
  "立希拎着鼓棒站在站台中央。看见爱音，眉头动了一下。",
  "taki 你怎么回来了。",
  "show character anon tease at left",
  "anon 这句话应该我问你吧？鼓棒不是'忘了'，是'放在练习室'了——对吧，Rikki？",
  "taki 彼此彼此。你那个是'落在长椅边'，不是'丢了'。",
  "anon 哇，抢我台词。今天大家都很会给东西换说法嘛。",
  "show character taki focus at right",
  "taki 快点收好，末班车要到了。",
  "show character anon normal at left",
  "anon 灯灯呢？先回去了？",
  "taki 嗯。散场就让她先走了。",
  "taki 她点头应了。",
  "show character anon tease at left",
  "anon 哦——稀奇，你居然舍得让她先走。",
  "taki 末班车要没了。她一个人在站台上吹风。",
  "show character anon scared at left",
  "两人并肩往检票口走。走出两步，爱音先停下。",
  "anon ……Rikki。",
  "taki 嗯？",
  "anon 检票口的站员呢？白手套那个大叔，刚才还冲我们打哈欠来着。",
  "play sound station_wind loop volume 35 fade 2",
  "show character taki frown at right",
  "show character anon shock at left",
  "立希顺着看过去。店招亮着，玻璃门里面，没有人。她转头看对面站台——空。换乘通道——空。整座站，只剩自动贩卖机嗡嗡地亮。",
  "taki ……末班车检票完了？",
  "anon::vn-impact 检票完了人也得从这儿出去啊！这么大一座站，五分钟，一个人都不剩？",
  "show character taki focus at right",
  "taki ……站务室。",
  "show character taki knock at right",
  "show character anon scared at left",
  "立希冲向站务室。门锁着，里面没灯。她砸了两下，等，再砸。爱音跑到站台边按下紧急呼叫键——听筒里一声短促的忙音。松开，再按。一样的忙音。",
  "anon::vn-impact 呼叫柱是坏的！不对，是没人接！两种可能都很糟你知道吗！",
  "show character taki frown at right",
  "立希点亮手机看了一眼。屏幕上是灯的对话框，最后一条还是傍晚发的那句\"到家了说一声\"。下面没有新消息。",
  "taki ……灯还没说到了。路上吧。",
  "show character anon soft at left",
  "anon 嗯，她到家肯定会发'到家了'的。每次都发，比你打卡还准时。",
  "show character anon scared at left",
  "show character taki focus at right",
  "两人对视一眼，不约而同压低了声音，像是怕把什么东西引来。",
  "show character anon strained at left",
  "anon ……我们再找一圈人。说不定谁躲在柱子后面睡觉。",
  "play sound camera volume 75",
  "show character anon photo at left",
  "show character taki frown at right",
  "第一圈。没有。第二圈。没有。回到原地时，爱音忽然举起手机，对着站台咔嚓一张。立希看她。",
  "anon 万一要发帖问呢。'有人遇到过吗，车站五分钟全空了'——配图我都想好了，标题就叫《深夜的羽丘车站消失了》。",
  "taki 你还有心情想标题。",
  "show character anon show_screen at left",
  "anon 我没有啊！我就是……手停不下来。你看，信号格呢？",
  { StageCue: {"mood": "uneasy", "effect": "signal-lost"} },
  "show character taki lean_in at right",
  "她把屏幕转向立希。信号格是空的——什么时候没的，两个人都没发现。爱音的表情垮下来一层。她关掉相机，又打开，又关掉。第三次，她把手机直接揣回兜里。",
  "show scene bg_yaneoka_passage with fadeIn",
  "show character taki lean_in at right",
  "show character anon show_screen at left",
  "爱音开始跑，立希跟着跑——通往站厅的楼梯，两人冲上去，跑到尽头，推开门——",
  { StageCue: {"mood": "uneasy", "effect": "loop"} },
  "show scene cg_run_loop with fadeIn",
  "还是站台。同一块黄地砖。同一个出口标志。",
  "anon ……啊？",
  "show scene bg_yaneoka_platform_night with fadeIn",
  "show character taki lean_in at right",
  "show character anon shock at left",
  "show character taki point_map at right",
  "立希没有说话。她盯着那块地砖看了两秒，掏出手机拍了一张，然后指着楼梯。",
  "show character taki focus at right",
  "taki 再走一次。慢一点。记住经过什么。",
  "show character anon scared at left",
  "anon 售票机、蓝色贩卖机、右转通道。记住了。你别走那么快——",
  "show scene bg_yaneoka_passage with fadeIn",
  "show character taki focus at right",
  "show character anon scared at left",
  "第二次。两人一步没错地走完通道。推开门。",
  { StageCue: {"mood": "uneasy", "effect": "loop"} },
  "show scene cg_run_loop with fadeIn",
  "还是那个站台。还是那块黄地砖。",
  "anon ……为什么啊。",
  "show scene bg_yaneoka_platform_night with fadeIn",
  "show character taki focus at right",
  "show character anon scared at left",
  "stop sound station_wind",
  "play sound notification volume 60",
  "show character taki reach_back at right",
  "show character anon shock at left",
  "爱音原地转了两个圈，猛地朝第三条岔路冲——立希一把拽住她的手腕。就在这时，立希的手机在口袋里震了一下。很轻的一声。两人都僵住了。",
  { StageCue: {"mood": "uneasy", "effect": "signal-one"} },
  "show character taki stiff at right",
  "show character anon scared at left",
  "立希掏出手机。屏幕右上角，信号格跳出了孤零零的一格。两条消息，前后脚撞了进来。",
  "灯： 立希ちゃん。车站，变得好奇怪。候车的人，突然就没有了。出口，走不出去。",
  "centered::vn-phone <span class=\"vn-cinematic-line\" style=\"--line-order:0\">灯： 我还在车站等你。</span><span class=\"vn-cinematic-line\" style=\"--line-order:1\">你回来的时候，先不要慌。</span><span class=\"vn-cinematic-line\" style=\"--line-order:2\">先找到我。</span>",
  { StageCue: {"mood": "uneasy", "effect": "signal-lost"} },
  "show character taki watery at right",
  "show character anon shock at left",
  "信号格抖了一下，归零。立希按着重拨，忙音。再拨。忙音。她的拇指悬在屏幕上，不动了。",
  "play sound station_wind loop volume 28 fade 1",
  "anon 灯灯她……她说她还在站里？！",
  "taki ……她没回去。",
  "anon 诶？",
  "taki 她说她还在等。她根本没走。",
  "taki ……她点头应了的。她答应了。",
  "show character anon scared at left",
  "anon 等、等等。'候车的人突然就没有了'——那她岂不是……她从头到尾都在这个站里？人都没的时候，她就一个人在这儿？",
  "show character taki guilt at right",
  "立希没有回答。她盯着那两条消息，指节慢慢收紧，屏幕边框被捏得咯的一声响。",
  "taki ……她一个人看到的。人消失的时候，她是一个人。",
  "show character anon soft at left",
  "show character taki watery at right",
  "anon 所以她才写'先不要慌'……她那个时候，就已经自己在想办法了吧。",
  "show character taki sharp at right",
  "立希猛地抬头，朝站台跑去。",
  "taki::vn-shout 灯——！！",
  "show character anon teary at left",
  "anon::vn-shout 灯灯——！灯灯！你在哪儿啊——！",
  "show character taki focus at right",
  "两人分头跑遍站台。喊名字。弯腰看长椅底下。冲进换乘通道。推开厕所的门。没有人。没有人。还是没有人。爱音扶着立柱，喘得上气不接下气。",
  "anon::vn-shout 为什么啊……她说她还在站里，可我们连她一个声音都听不到！同一座站！同一座站啊！",
  "taki 出站。找人。报警。随便什么——先出去再说。",
  "两人再一次冲上楼梯。第三次。推开门——黄地砖。出口标志。原点。",
  "show character taki sharp at right",
  "show character anon shock at left",
  "立希一脚踹在墙上，又收住。她站在原地，肩膀起伏。爱音第一次看见她这个样子。",
  "呼叫柱。忙音。站务室。锁着。电话。没拨号音。手机。无服务。电子时刻表\"啪\"地跳了一下——下一班列车的倒计时停在 00:00，秒数不动了。",
  "show character taki guilt at right",
  "show character anon scared at left",
  "站里彻底安静下来。",
  { StageCue: {"mood": "tense", "effect": "none"} },
  "taki ……是我不好。",
  "show character anon shock at left",
  "anon 诶？",
  "taki 是我叫她先回家的。她还说'嗯'，好好地应了我。",
  "taki 结果她根本没走成。人没有的时候，她一个人在这里。从那个时候，等到现在。",
  "show character anon strained at left",
  "show character taki stiff at right",
  "anon::vn-shout 现在算这个有什么用啊！",
  "show character taki guilt at right",
  "立希闭嘴了。安静了两秒。",
  "show character taki sharp at right",
  "taki ……那你有什么办法吗。",
  "show character anon shock at left",
  "anon ……什么？",
  "show character anon strained at left",
  "taki::vn-tense 你说'有什么用'。那你有办法吗。出口走不出去。电话打不通。她明明就在这座站里，我们连她的声音都找不到。",
  "taki::vn-tense 你有办法吗。",
  "show character taki watery at right",
  "anon::vn-shout 我没有！你就有吗？！你从刚才开始就会说'再找一遍''慢一点''记下来'——然后呢？！哪一样有用了吗？！",
  { StageCue: {"mood": "uneasy", "effect": "none"} },
  "show character anon apologetic at left",
  "立希的表情停住了。半秒。爱音看见她眼眶红了一圈，又硬生生忍回去。爱音的话卡在喉咙里。",
  "anon::vn-soft ……对不起。我不是那个意思。我就是……我也怕啊。灯灯她明明就在这附近的什么地方，说不定正隔着一条通道听我们吵架，可是我们——",
  "show character anon scared at left",
  "show character taki focus at right",
  "隧道深处，风先到了。",
  { StageCue: {"mood": "uneasy", "effect": "arrival"} },
  "紧接着是铁轨的震动，然后是灯光，从弯道那头一点点漫出来。两个人的争吵声卡在喉咙里，同时闭嘴。",
  "show scene cg_arrival with fadeIn",
  "立希把爱音往身后带了半步。列车减速，进站，停稳。车门打开，车厢里的灯亮着。车头显示屏上，是平时会经过的方向。",
  "anon （喘着气）……这班车，时刻表上没有。",
  "taki （喘着气）……嗯。",
  "anon 开去哪儿，谁也不知道。",
  "taki 留在这儿，哪儿也去不了。",
  "沉默。风声。爱音忽然小声笑了一下，笑得不太成功，带着鼻音。",
  "anon ……刚才吵架的时候，我突然想明白一件事。",
  "taki ……什么？",
  "anon 我们俩刚才那样互相吼，是因为身边只剩对方了啊。",
  "taki ……嗯。我知道。",
  "爱音吸了吸鼻子，盯着那扇开着的车门。",
  "anon ……总觉得啊。现在不上这班车的话，就真的、再也见不到灯灯了。",
  "taki ……嗯。我也是这么想的。",
  "show scene cg_boarding with fadeIn",
  "两人对视一眼。谁也没有说服谁，谁也不需要被说服。立希先踏上去，在门边停住，回身伸出手。爱音抓住那只凉的手，跨了进去。立希等她站稳才松开。",
  { StageCue: {"mood": "uneasy", "effect": "blackout"} },
  "stop sound station_wind",
  "车门合拢的一刻，站台顶上熄了一盏灯。",
  "jump Scene2"
],
"Scene2": [
  function () { return MygoChapter.enter("Scene2"); },
  "show scene bg_train_interior_night with fadeIn",
  "play sound train_rumble loop volume 38 fade 2",
  "show character anon apologetic at left",
  "show character taki guilt at right",
  "车厢里很静。刚才吵过的两个人，一个靠着车门，一个扶着立柱，谁也没先开口。过了几秒，爱音把掉在地上的补光夹捡起来，用袖子擦了擦，忽然低声开口。",
  "anon ……刚才那句'哪一样有用了吗'，对不起。说得太过头了。",
  "show character anon soft at left",
  "taki ……我也是。'你有办法吗'那句，收回。",
  "anon ……嗯。",
  "show character taki focus at right",
  "taki 没完呢。到了下一站，接着找她。",
  "anon 嗯！",
  "show character anon look_phone at left",
  "爱音吸了吸鼻子，点亮手机。信号格是空的——但屏幕下方，无线网一栏里，多了一个不知道从哪儿连上的、名字空白网络。她点开那个论坛图标。",
  "anon ……喂。你看这个。没信号，可这东西刷新得动。",
  "show character taki lean_in at right",
  "taki 论坛？",
  "show character anon normal at left",
  "anon 我常潜的那个怪谈板。平时就看看，不说话的那种——喂，谁会用自己的名字发怪谈帖啊，会被扒的。",
  "show character anon scared at left",
  "anon 可是……没网它凭什么刷得动啊。",
  function () { MygoForumBridge.open(); return true; },
  "show character anon show_screen at left",
  "她点开自己的头像。资料页弹出来。",
  "anon 账号，ano_reader。身份，会员。帖子数，零——看，我就说我是潜水的。",
  "show character anon shock at left",
  "anon ……诶。",
  "taki 又怎么了。",
  "show character anon look_phone at left",
  "anon 这个页面……它在动。右上角那个小圈，转了一圈，页面就闪一下。我没点刷新啊。",
  "show character taki knock at right",
  "立希凑过来看了一眼，直起身，走到驾驶室隔窗前敲了两下——没回应。回来时爱音还举着手机。",
  "show character taki focus at right",
  "taki 它多久闪一次？",
  "show character anon tease at left",
  "anon 我哪知道，我又没有体内秒表——啊，等等，你有。",
  "show character taki drum_knees at right",
  "taki ……我用打的。你盯屏幕，我数。",
  "show character anon count_beats at left",
  "anon 好。一人顾一边。",
  "立希把鼓棒抵在膝盖上，极轻地点。一下，两下——页面闪了一下。",
  "taki 十秒。",
  "anon 十秒一次？",
  "taki 十秒一次。",
  "show character anon look_phone at left",
  "anon 再来一次。……来了。十秒。它在反复读我的资料页。为什么啊？我又没让它读。",
  "show character taki normal at right",
  "taki ……像有人按了循环播放。",
  "show character anon pout at left",
  "anon 这种形容你就不能憋回去吗！",
  "show character taki reach_back at right",
  "show character anon look_phone at left",
  "立希盯着那个十秒一次的小圈看了几秒，忽然伸手按住爱音拿手机的手腕，往下压。",
  "show character taki focus at right",
  "taki 先收起来。省电。到了站上再说。",
  "show character anon scared at left",
  "anon ……哦。",
  "show scene bg_train_interior_night-dim with fadeIn",
  "show character anon scared at left",
  "show character taki focus at right",
  "爱音把手机揣回兜里，目光顺着过道扫了一圈，一个一个数。立希没数，她直接走到最近的乘客旁边，弯腰，看了看对方的胸口，又直起身，把爱音往后拨了半步。",
  "anon （压着声音）他们……都在睡？",
  "taki 呼吸有。别碰。",
  "show character anon strained at left",
  "anon 我没打算碰！谁会去碰陌生人啊！我只是——这么多人，一个人都不醒，你不觉得这个难度很离谱吗？集体午休也没这个质量的。",
  "taki ……嗯。",
  "show character anon scared at left",
  "anon 你'嗯'什么，这种时候你不是应该吐槽我吗。",
  "show character taki knock at right",
  "show character anon soft at left",
  "立希没接话。她走到驾驶室隔窗前，敲了两下。没回应。又敲，指节加重。爱音看着她的背影，忽然小声开口。",
  "anon Rikki。你的手。",
  "show character taki normal at right",
  "show character taki knock at right",
  "taki 干什么。",
  "anon 你在打拍子。另一只手，从上车开始就在腿上打拍子。",
  "show character taki frown at right",
  "show character taki drum_knees at right",
  "taki ……习惯。",
  "anon 你排练赶进度的时候才打拍子。",
  "show character taki focus at right",
  "taki ……过了这站再说。你站到车厢里面来，别贴着门。",
  { StageCue: {"mood": "uneasy", "effect": "passing"} },
  "show scene cg_passing with fadeIn",
  "爱音乖乖往里挪了两步。列车速度不减。窗外，一个亮着灯的站台滑过去——没有任何减速的意思。两人同时扑到窗边。",
  "anon::vn-impact 刚才那是站吧？！有站牌有灯的！为什么不停啊？！末班车开过站，正常世界不会发生这种事吧？！",
  "show scene bg_train_interior_night-passing with fadeIn",
  "show character anon soft at left",
  "show character taki focus at right",
  "show character anon press_window at left",
  "show character taki point_map at right",
  "taki ……线路图。",
  "show character anon photo at left",
  "立希指着车门上方。屏幕上，当前站的名字还是她们上车的那个站。走过一站，一个字都没动。爱音掏出手机想拍，手一抖，糊了。再拍，还是糊。",
  "show character anon scared at left",
  "show character taki focus at right",
  "anon 拍不了……手抖。",
  "show character taki point_map at right",
  "show character taki reach_back at right",
  "taki 给我。",
  "anon 你的手在打拍子。",
  "taki ……拿稳了拍。",
  "show character taki focus at right",
  "show character anon look_phone at left",
  "立希接过手机，拍了一张，还给她。爱音盯着那张照片看了几秒，忽然开口。",
  "show character anon tease at left",
  "anon ……我说，得给这趟车起个名字。",
  "show character taki frown at right",
  "taki 给它？",
  "anon 总不能一直'这趟车''那趟车'地叫。回头要是能出去，跟人讲起来连个称呼都没有——'深夜幽灵号'，怎么样？",
  "show character anon pout at left",
  "taki 不要给怪谈起名字。",
  "anon 为什么啊！有名字才记得住啊。",
  "show character taki focus at right",
  "show character anon strained at left",
  "taki 现在称呼它，它叫'我们要查的东西'。名字起早了，人会照着名字去找线索。",
  "show character anon normal at left",
  "anon 好严肃……那，'谜之电车'。",
  "taki '谜'是我们正在解的部分，不能当名字。",
  "show character anon tease at left",
  "anon '末班车PLUS'。",
  "taki 哪来的PLUS。",
  "anon 比平时多的意思啊！多载了我们两个，多开了一个不存在的站！",
  "show character anon shock at left",
  "taki ……要起就两个字以内。我好念，记录里也省地方。",
  "anon 诶，你要用？",
  "taki 核对的时候总得有个称呼。",
  "show character anon tease at left",
  "anon 那——'怪车'。你念一遍试试，念着不瘆的话，就定它。",
  "show character anon scared at left",
  "taki 怪车。",
  "anon::vn-tense …………瘆。换。",
  "taki 是你起的。",
  { StageCue: {"mood": "uneasy", "effect": "rhythm"} },
  "play sound station_signal volume 70",
  "show character anon count_beats at left",
  "show character taki drum_knees at right",
  "车轮声忽然变了调——车厢里响起进站提示音。爱音下意识跟着数：短、短、短……长。立希的手指在膝盖上跟着点完，两人对视一眼。",
  "taki 三短一长。",
  "anon ……记住了。你肯定记得住。",
  "taki 我是鼓手。",
  "jump Scene3"
],
"Scene3": [
  function () { return MygoChapter.enter("Scene3"); },
  "show scene cg_sign with fadeIn",
  "stop sound train_rumble",
  "play sound station_wind loop volume 30 fade 1",
  "play music mystery loop volume 55 fade 2",
  "立希先探身出去，左右看了看，才让爱音下车。爱音下车很慢，一只手一直抓着立希的袖子。立希没有甩开。两人站在站牌下，抬头。",
  "anon き・さ・ら・ぎ・駅。",
  "taki 认识？",
  "anon ……啊。",
  "taki '啊'是什么意思。",
  "anon 是'我好像在哪儿见过'的意思！",
  "anon ……等等。我的论坛。刚才车上还能刷的那个——",
  function () { MygoForumBridge.open(); return true; },
  "show scene bg_kisaragi_platform with fadeIn",
  "show character anon clutch_sleeve at left",
  "show character taki focus at right",
  "show character anon look_phone at left",
  "她点亮手机。那个空白名字的网络还在。论坛还在。首页上，置顶的只有一个帖子。她点开。",
  "anon 《如月车站》……发帖日期好老。就是它！我看过这个！好多年前，有人直播说自己坐电车坐到了不存在的车站——",
  "show character taki lean_in at right",
  "她往下滑，越滑手指越慢。立希在她身侧看着屏幕。",
  "show character anon scared at left",
  "anon '电车很久不停站。''乘客全在睡。''驾驶室没有人应。''最后停在地图上没有的车站。'……",
  "show character taki frown at right",
  "anon Rikki。全中。一个不落。",
  "show character taki focus at right",
  "taki 后面呢？",
  "show character anon strained at left",
  "anon 后面是别的版本，乱七八糟，我以前没敢看完……现在庆幸没看完。省得我对着'剧本'找线索，那不就真成恐怖片观众了吗。",
  "show character taki faint_smile at right",
  "taki ……你难得靠谱。",
  "show character anon pout at left",
  "anon 我一直都靠谱好吗！只是平时被你吼得没机会展示！",
  "show character taki focus at right",
  "她下意识去点回复框。点了三下。没有反应。",
  "anon ……连回帖都不行。只读。这论坛防我防得跟防贼一样。",
  "show character taki frown at right",
  "立希已经走向站务室。门锁着，里面没灯。她试了试旁边的电话，拿起来听了一下，放回去。",
  "taki 没拨号音。",
  "show character anon show_screen at left",
  "anon 站厅那头的呼叫柱倒是一直亮着……喂，Rikki，我们站里那根呼叫柱是坏的，这根会不会能通？",
  "show character taki focus at right",
  "taki 待会儿试。先看能看的。",
  "show character anon look_phone at left",
  "爱音点开自己的资料页，又看了一遍。",
  "anon ano_reader。会员。帖子零。回复零。……我的简介还是空的。",
  "她随手在简介栏里敲了两个字又删掉，按了保存。页面闪了一下。",
  "show character anon show_screen at left",
  "anon '已保存'。……我明明什么都没写。",
  "anon 保存是保存了……可它回给我的东西，怎么比我自己填的还多？",
  "show character taki lean_in at right",
  "她划到论坛最下面，有一个\"版务\"的入口。她点进去。",
  "show character anon pout at left",
  "屏幕上只跳出一行字：无权访问。",
  "anon ……版务页，点不开。会员不让看，正常。",
  "anon 但是你看这儿——版务下面挂着一行小字，'暂存（未同步）'。后面还拖着一句，'调度窗口未开启'。",
  "show character taki frown at right",
  "taki ……什么意思？",
  "show character anon scared at left",
  "anon 暂存了一份东西。我看不到。它说，还没到能看的时候。",
  "anon 没有名字，没有日期，连个数都不给。只告诉我'未同步'。",
  "show scene bg_kisaragi_platform-pillar with fadeIn",
  "show character anon scared at left",
  "show character taki frown at right",
  "show character anon look_phone at left",
  "show character taki focus at right",
  "两人对着那行小字看了几秒。立希先移开视线，看了一眼站厅另一端——紧急呼叫柱的指示灯亮着，一明，一暗。",
  "taki 灯说出口走不出去。电话、站务室，全是死的。要是有哪个部分还'活着'——",
  "taki 我去试那根柱子。",
  "anon 好。我盯手机。有动静我叫你。",
  "taki ……别走到站台边上。",
  "show character anon soft at left",
  "anon 知道啦。倒是你，别走太远。",
  "jump Checkpoint"
],
"Checkpoint": [
  function () { return MygoChapter.enter("Checkpoint"); },
  "show scene bg_kisaragi_passage with fadeIn",
  "show character anon look_phone at left",
  "show character taki focus at right",
  "爱音还盯着版务页脚那行\"暂存（未同步）\"的小字。同一时刻，立希看了一眼呼叫柱，抬脚就走。",
  "taki 还是没动静？我去按呼叫柱。能通的话，就说明这套站还有会'应'的部分。",
  "show character anon shock at left",
  "anon 等——等一下啦！",
  "show character taki slow_turn at right",
  "show character anon strained at left",
  "立希的脚步钉住了。半秒。她回过身。",
  "show character taki frown at right",
  "taki ……你说。快。",
  "anon 不是'快'的问题……呼。好，我快说。柱子、论坛，还有这个站，从车上开始就感觉是一套东西。你按下它，这站就会'应'我们一次——我手机上说不定会有动静。",
  "show character taki gentle at right",
  "anon 所以你按，可以。但你按完别走开。我盯着手机，它一响我就叫你。我们俩一起看。",
  "taki ……嗯。",
  "show character anon shock at left",
  "anon ……嗯？",
  "taki 刚才没听完就要走，是我的问题。（转身往呼叫柱走）就转角后面，叫一声听得见。按完我回来。",
  "show character anon soft at left",
  "anon ……哦。哦！好！",
  { StageCue: {"mood": "tense", "effect": "notice"} },
  "play sound notification volume 70",
  "show character anon shock at left",
  "show character taki focus at right",
  "立希走向站厅的呼叫柱。按下。听筒里没有人声——但一秒后，爱音手里的手机\"叮\"地响了一声。",
  function () { return MygoChapter.start(); },
  "jump ChallengeIntro"
],
"ChallengeIntro": [
  function () { return MygoChapter.enter("ChallengeIntro"); },
  "论坛自己弹到了最前面。两条提示，上下排着。",
  "centered::vn-warning <span class=\"vn-cinematic-line\" style=\"--line-order:0\">调度窗口开启。</span>",
  "版务暂存区已同步 1 份报告 #71。（当前身份暂无阅读权限）",
  "show character anon scared at left",
  "anon::vn-impact 来了来了来了！窗口开了——四分钟！它给我四分钟！",
  "anon::vn-impact 可是那份报告……我点不开！'暂无阅读权限'！它给了我时间，却不给我看的东西，这算什么啊！",
  "show character taki focus at right",
  "taki （从转角回头）那就想办法看。四分钟。",
  "show character anon strained at left",
  "anon::vn-shout 、知道了！你别催！",
  "jump ChallengeWait"
],
"Reminder120": [
  function () { return MygoChapter.enter("Reminder120"); },
  "show character anon look_phone at left",
  "show character taki block_wind at right",
  "倒计时走到 02:00，手机震了一下，屏幕上浮出一行小提醒。爱音的手指在屏幕上敲了又删。立希站在转角，没有催，只把她自己那侧的路灯用身体挡了挡风。",
  "show character anon scared at left",
  "anon （忽然，没回头）Rikki。骂我一句吧。",
  "taki （在转角）……现在？",
  "show character anon strained at left",
  "anon 凶的那种。像排练时我说'再练五分钟'，你会说的那种。",
  "show character taki frown at right",
  "show character taki block_wind at right",
  "taki 为什么。",
  "show character anon scared at left",
  "anon 恐怖片里都有这招。想确认身边的人是真的，就让她讲一句只有她会讲的话。",
  "show character taki focus at right",
  "立希沉默了两秒。然后她是真的想了想，才开口。",
  "show character taki sharp at right",
  "taki 爱音。你早进的那半拍，全乐队只有你自己觉得听不出来。",
  "show character anon soft at left",
  "show character taki gentle at right",
  "anon ……够凶。是你。确认完毕。",
  "taki 一句就够的话，别攒到现在。",
  "show character anon look_phone at left",
  "anon （转回去，盯着屏幕）两分钟了。圈圈，你倒是转快点。",
  "jump ChallengeWait"
],
"Reminder60": [
  function () { return MygoChapter.enter("Reminder60"); },
  "show character anon teary at left",
  "show character taki block_wind at right",
  "倒计时走到 00:58，又一声。爱音的呼吸越来越快。",
  "anon （对着手机，小声）快点啊……谁都好，把那份东西给我看看……",
  "jump ChallengeWait"
],
"Success": [
  function () { return MygoChapter.enter("Success"); },
  "play sound notification volume 80",
  "show character anon shock at left",
  "show character taki focus at right",
  "忽然，手机\"叮\"的一声，比前面任何一次都亮。",
  "show character anon look_phone at left",
  "show character taki lean_in at right",
  "论坛自动跳转。那条\"暂无权限\"的报告，摊开在了她面前。",
  "版务报告 #71（暂存）",
  "回程调度：B7 号站台。",
  "进站提示音：三短一长。",
  "登车前，先核对车头显示的站名。",
  "投稿：◆xmKsragiEki",
  "show character anon excited at left",
  "show character taki focus at right",
  "爱音盯着屏幕，两秒没出声——然后她深深吸了一口气，转身朝转角喊，声音是破的。",
  "anon::vn-shout Rikki！！有报告！回程的！它自己弹到我手机上来了！",
  "taki （声音从转角传来，紧接着人出现，走得很快）念。",
  "show character anon show_screen at left",
  "anon B7号站台！提示音三短一长——跟进站那声一样！还有，'登车前先核对车头显示的站名'！",
  "show character anon normal at left",
  "show character taki frown at right",
  "taki 谁写的。",
  "show character anon scared at left",
  "anon 一个乱码名字。看不懂——像是……不想被人认出来的那种。",
  "show character anon strained at left",
  "show character taki focus at right",
  "两人对视。沉默一拍。立希先开口，声音很稳。",
  "taki 不知道是谁的，就先别全信。三样都对得上的话——再上车。",
  "show character anon soft at left",
  "anon 嗯。B7号站台。走。",
  function () { return MygoEnding.checkpoint(1); },
  "show scene bg_kisaragi_platform-no1 with fadeIn",
  "show character anon soft at left",
  "show character taki focus at right",
  "show character anon scared at left",
  "两人小跑着换到 B7 号站台。空。长椅空。立希站到站台边缘最安全线后半步，回头确认爱音站进了她身侧。",
  "taki （盯着隧道深处）……来了。'怪车'。",
  "show character anon pout at left",
  "anon 你怎么还真用它啊！！说瘆的人是我吧！！",
  "taki 两个字，好念。",
  "show character anon tease at left",
  "show character anon soft at left",
  "anon ……那，定案了。名字定案了！",
  { StageCue: {"mood": "uneasy", "effect": "rhythm"} },
  "show scene cg_signal with fadeIn",
  "stop music mystery",
  "play sound station_signal volume 70",
  "隧道深处，隐隐传来一声提示音——爱音跟着立希的手指，一个一个数。",
  "taki ……短。短。短。长。",
  "anon::vn-impact 三短一长！对上了！",
  { StageCue: {"mood": "uneasy", "effect": "arrival"} },
  "show scene cg_train_head with fadeIn",
  "远处，灯光。列车减速，进站。车头的显示屏亮着——两人同时抬头。",
  "taki （一个字一个字地读）……是我们上车的那个站。",
  "anon::vn-impact 站名对。提示音对。站台对。三样全对上了！",
  "stop sound station_wind",
  "taki ……好。上车。",
  "anon 喂——那句'对上了'，就不多问一句是谁帮的吗？",
  "taki 要问，等接到了灯再问。车在等。",
  "anon 你——！！……算了，路上补！",
  "jump Scene5"
],
"BadEnd": [
  function () { return MygoChapter.enter("BadEnd"); },
  "show scene bg_kisaragi_passage with fadeIn",
  "stop music mystery",
  "stop sound train_rumble",
  "play sound station_wind loop volume 25 fade 1",
  "倒计时归零。手机\"叮\"的一声——论坛上那行字变了：",
  "centered::vn-warning <span class=\"vn-cinematic-line\" style=\"--line-order:0\">调度窗口已关闭。</span>",
  "版务暂存的那一行灰了下去。远处传来列车驶过轨道的声音——没有减速。",
  "show scene bg_passage_loop_bad with fadeIn",
  "爱音站起来，朝转角喊立希。站厅里没有回声。她快走几步，再走——脚下的通道拐了一个不该存在的弯。她停住，回头，来路变得很长。墙的另一边，隐隐传来立希的声音，在叫她的名字，很稳，一声一声，像在沿着什么东西找过来。",
  "show scene cg_badend with fadeIn",
  "爱音回到长椅边。屏幕灰着。她掏出手机——信号格空着，但短信输入框还开着，收件人：灯。她打字：",
  "灯灯，收到了。你写得对，出口走不出去。但是刚才有一点线索，就差一点点。Rikki在想办法，我会找到她，然后我们一起回去找你。你先照你消息里说的做：别乱走，站在亮的地方。",
  "打到这里，她停住，全选，删掉。重新打：",
  "centered::vn-unsent <span class=\"vn-cinematic-line\" style=\"--line-order:0\">灯灯。</span><span class=\"vn-cinematic-line\" style=\"--line-order:1\">等我。</span>",
  { StageCue: {"mood": "isolated", "effect": "rhythm"} },
  "play sound station_signal volume 70",
  "发送。状态：发送中。圈圈转着。墙那边传来三下短促的敲击，停了一拍，又是一声长响——立希用鼓棒，敲的正是那个节奏。爱音猛地望向转角，起身迈出一步。画面暗下。立希仍在另一侧找她。",
  "centered::vn-ending <span class=\"vn-cinematic-line\" style=\"--line-order:0\">BAD END｜未送达</span>",
  { Choice: { Retry: { Text: '从场景四检查点重试', Do: 'jump Retry' }, Exit: { Text: '返回标题', Do: 'end' } } }
],
"Scene5": [
  function () { return MygoChapter.enter("Scene5"); },
  function () { return MygoEnding.checkpoint(2); },
  "show scene cg_reunion with fadeIn",
  "stop music mystery",
  "stop sound station_wind",
  "列车停稳，车门打开。灯抬起头，站起来。立希几乎是小跑过去的，爱音慢半步跟在后面。",
  "show scene bg_yaneoka_platform_night with fadeIn",
  "show character anon soft at left",
  "show character taki gentle at right",
  "show character tomori stand at center",
  "灯先迎了两步，把立希从上到下看了一遍，又看爱音——看她们完整不完整。",
  "tomori 立希ちゃん。你们，没有受伤吧。",
  "taki 没有。",
  "anon 没事没事！就是腿到现在还在抖。灯灯你才吓人呢，一个人在这种地方——害怕了吧？",
  "show character tomori earnest at center",
  "tomori ……有一点。后来，不太怕了。",
  "show character taki frown at right",
  "taki ……为什么。",
  "play music reunion loop volume 55 fade 3",
  "show character tomori steady at center",
  "tomori 能做的事，我一件一件，写下来了。",
  "show character tomori reach_hand at center",
  "立希把灯的包接过来挎上，再握住她的手，眉头拧起来。",
  "show character taki gentle at right",
  "taki 手怎么这么凉。",
  "show character tomori earnest at center",
  "tomori 风，有一点。",
  "taki （声音压得很低，不是质问）……为什么还在这里。我叫你先回家的。你答应了的。",
  "tomori 嗯。本来，要走的。",
  "show character tomori show_phone at center",
  "show character taki lean_in at right",
  "show character anon lean_whisper at left",
  "灯抽回手，把手机屏幕点亮，转向立希和爱音。备忘录里，是她一条一条记下来的东西。",
  "候车的人，没有了",
  "出口，试了两次，都绕回来了",
  "手机，没有信号了",
  "立希ちゃん回来的时候，先找到我",
  "tomori 刚要走的时候，站员，不见了。人，一下子就没有了。我觉得，不对。",
  "tomori 出口，走了一遍。绕回来。又走了一遍。还是绕回来。消息里写的，就是这个。",
  "show character anon soft at left",
  "anon （小声）……我们也走了两遍。一模一样。",
  "show character tomori steady at center",
  "tomori 嗯。所以我想，这里，是走不出去的。",
  "show character taki watery at right",
  "taki ……那你也该——",
  "tomori 乱走的话，立希ちゃん回来，就找不到我了。",
  "show character tomori hug_bag at center",
  "立希说不出话了。灯把手机收回来，抱在怀里，继续说，很平静。",
  "tomori 所以坐在这里。最亮的地方。立希ちゃん一回来看得到的地方。",
  "tomori 还有，这个记录，想当面给立希ちゃん看。发消息的话，会没信号。",
  "show character tomori steady at center",
  "tomori 所以，不是走不掉。是决定等的。",
  "show character taki reach_back at right",
  "show character tomori reach_hand at center",
  "立希看着她，好几秒。然后她把灯的包重新拎好，又伸手把灯的手握回来，往站厅方向带。",
  "show character taki gentle at right",
  "taki ……嗯。先进去。里面有暖气。",
  "show character tomori earnest at center",
  "走了两步，立希忽然又开口，声音很轻。",
  "show character taki faint_smile at right",
  "taki ……灯。",
  "show character tomori small_smile at center",
  "tomori 嗯。",
  "show character taki gentle at right",
  "taki 下次，我不说'不用等我'了。",
  "tomori 嗯。",
  function () { return MygoEnding.checkpoint(3); },
  "show character anon lean_whisper at left",
  "show character taki shy at right",
  "爱音在旁边小声嘀咕。",
  "anon 刚才在怪谈空间里都没见你这么紧张。",
  "show character taki sharp at right",
  "taki 你说什么？",
  "show character anon shock at left",
  "anon 没什么！我说'外面好冷'！真的！",
  { StageCue: {"mood": "warm", "effect": "signal-restored"} },
  "show scene bg_yaneoka_concourse_night with fadeIn",
  "show character anon shock at left",
  "show character taki sharp at right",
  "show character tomori small_smile at center",
  "play sound notification volume 55",
  "show character anon look_phone at left",
  "show character taki gentle at right",
  "三人往站厅走。这一次，检票口就只是检票口，通道通向站外，没有绕回任何站台。走到一半，爱音兜里的手机一连串地震动起来——顶栏的信号格一格一格爬满，迟到的通知往下砸。",
  "anon （掏出手机）……信号回来了。",
  "show character tomori write_memo at center",
  "show character anon lean_whisper at left",
  "灯按亮自己的手机看了一眼，然后打开备忘录，在最后一行下面，慢慢添了一行。",
  "centered::vn-memo <span class=\"vn-cinematic-line\" style=\"--line-order:0\">信号，回来了。</span><span class=\"vn-cinematic-line\" style=\"--line-order:1\">出口，能出去了。</span><span class=\"vn-cinematic-line\" style=\"--line-order:2\">立希ちゃん，回来了。</span>",
  "anon （凑过去看，小声）……我们也被写进记录里了啊。",
  "tomori 嗯。今天的事，全部。",
  "show character taki normal at right",
  "show character tomori small_smile at center",
  "taki 爱音。",
  "show character anon normal at left",
  "anon 在。",
  "taki 那份报告的事。你说要路上讲的。",
  "show character anon shock at left",
  "anon 咦，你还记得啊。",
  "taki 是你自己答应的。讲。",
  "show character anon tease at left",
  "anon 现在就想听？",
  "taki 你要是想攒着回学校讲，也可以。",
  "anon 那还是现在讲吧！从头讲吗？好长哦。重点讲？……重点我也会讲到的，大概。",
  "show character taki frown at right",
  "taki ……最好是。",
  "show character anon pout at left",
  "anon 为什么一定要补这句啊！",
  "show character tomori pull_sleeves at center",
  "show character anon shock at left",
  "show character taki normal at right",
  "灯在旁边轻轻笑出声。爱音和立希同时看她。灯只是摇了摇头，把两个人的袖子各拽了一下，往前指。",
  "tomori 今天，先不回家。",
  "anon 诶？",
  "show character tomori small_smile at center",
  "tomori 去我家。跟爸爸说过了，可以。你们也，问一下家里。",
  "tomori 立希ちゃん是第一次，进门。",
  "show character anon normal at left",
  "anon 那我呢？",
  "tomori 嗯。也是。",
  "show character anon cheer at left",
  "show character taki shy at right",
  "爱音\"哦哦\"地就要欢呼——立希没有出声。她侧过脸去看时刻表，看了两秒，什么都没看进去，耳朵红了。",
  "show character anon lean_whisper at left",
  "anon （凑近，压低声音）喂。耳朵红了。",
  "taki 外面冷。",
  "show character anon tease at left",
  "anon 我的耳朵怎么不红。",
  "show character anon normal at left",
  "立希不答。她用沉默申请终止这个话题，耳朵却更红了。爱音掰着手指头算了算，忽然咦了一声。",
  "show character anon sly at left",
  "anon 啊，不对。这一次，我算不上'第一次'吧？之前来接灯灯的那天早上，我就在灯灯家等素世同学来着——进去等的。灯灯还送了我创可贴，海洋生物的，十二只装。",
  "show character taki slow_turn at right",
  "show character anon shock at left",
  "立希保持着看时刻表的姿势，缓缓地、整个头转了过来。",
  "taki ……'在灯家等'？",
  "show character anon normal at left",
  "anon 嗯？啊，对。",
  "show character tomori earnest at center",
  "tomori 嗯。来过。",
  "show character taki stiff at right",
  "立希看看爱音，又看看灯，最后看向自己的鞋尖。半晌，问出来的却是——",
  "taki ……我送到门口的次数。",
  "show character tomori steady at center",
  "tomori 很多次。",
  "taki 进门呢。",
  "tomori 今天之前，零次。",
  "show character taki look_away at right",
  "show character anon tease at left",
  "立希转回去，继续研究那张提供不了任何答案的时刻表。爱音后知后觉地收了声，两秒后没忍住。",
  "anon 可是窗帘真的超可爱哦？还有灯灯床头摆的那——",
  "show character taki shy at right",
  "taki 不要剧透。",
  "show character anon pout at left",
  "anon 为什么啊！",
  "show character taki look_away at right",
  "taki （不看她）到了，自然会看到。（掏出手机）……打电话。",
  "show character taki shy at right",
  "show character anon sly at left",
  "立希的电话最先打完。她收起手机站在原地，嘴唇微微动着，像在对一张只有她自己看得见的清单。",
  "taki （小声）……明早的东西，在灯家附近买……",
  "anon 听到了哦。",
  "taki 我什么都没说。",
  "anon 连早饭在哪家便利店买都盘算上了。……啊，不对，刚才不听剧透的时候，我就该发现的。",
  "taki 发现什么。",
  "show character anon tease at left",
  "anon 没什么～超级期待的那种～",
  "taki ……快打你的电话。",
  "show character anon excited at left",
  "anon 我也问。等下！——补光夹！这回终于能派上用场了！",
  "show character anon photo at left",
  "show character taki gentle at right",
  "show character tomori small_smile at center",
  "爱音打完电话，两人对视一眼，点头。爱音把补光夹卡到手机上，打开灯。",
  "anon 来来，站位站位。灯灯中间——不对，灯灯本来就习惯后面……那灯灯中间，Rikki 你左边——喂，你太往边上去了！",
  "taki 没开闪光吧。",
  "anon 有补光夹，谁还需要闪光灯啊。你看，带它回来还是有用的吧？",
  "show character tomori pull_sleeves at center",
  "taki ……嗯。站近一点。别把灯挤到边上。",
  "show character tomori small_smile at center",
  "tomori 再一点。",
  "taki ……这样可以了吧。",
  "show character taki faint_smile at right",
  "anon 可以了可以了。三、二、一——",
  { StageCue: {"mood": "warm", "effect": "shutter"} },
  "show scene cg_photo with fadeIn",
  "play sound camera volume 75",
  "快门响。爱音凑在屏幕前看：三个人的脸挤在一起，立希不习惯地绷着嘴角，灯在笑。",
  function () { return MygoEnding.checkpoint(4); },
  "anon 原样留着，不加滤镜。……等明天人齐了，再拍一张五人的。",
  "她锁上手机。锁屏前的最后一瞬，通知栏里那条没有署名的返程报告推送还亮着——投稿那一栏，只挂着一串看不懂的乱码。",
  "anon ……说起来。刚才好像有人帮了我们。",
  "tomori 还有别人，在车站吗？",
  "taki 灯，没事。（把灯往站厅里带半步）爱音，你少说这种吓人的话。外面冷，先走。",
  "anon 知道啦知道啦。走在最后的人可是我哦，麻烦让让——",
  { StageCue: {"mood": "warm", "effect": "none"} },
  function () { return MygoEnding.checkpoint(5); },
  "show scene bg_yaneoka_platform_night with fadeIn",
  "show character anon soft at left",
  "show character taki gentle at right",
  "show character tomori earnest at center",
  "三人并肩离开站台。画面停在恢复了走动的时刻表上。",
  "stop music reunion with fade 2",
  "centered::vn-ending <span class=\"vn-cinematic-line\" style=\"--line-order:0\">END｜下一班，终于对了</span>",
  function () { return MygoEnding.reward(); },
  "end"
],
"ChallengeWait": [
  { MygoInvestigation: true }
],
"Retry": [
  function () { return MygoChapter.retry(); },
  "jump Checkpoint"
]
});
